[package]
name = "trait-for-collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-smithy-types = "0.55.2"
serde_json = "1.0.96"
